server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loan/**
  discovery:
    locator:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
